name: ConceptualSpaces
channels:
- defaults
dependencies:
- cairo=1.14.8=0
- certifi=2016.2.28=py27_0
- cycler=0.10.0=py27_0
- dbus=1.10.20=0
- expat=2.1.0=0
- fontconfig=2.12.1=3
- freetype=2.5.5=2
- glib=2.50.2=1
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=0
- icu=54.1=0
- jpeg=9b=0
- libffi=3.2.1=1
- libgcc=5.2.0=0
- libgfortran=3.0.0=1
- libiconv=1.14=0
- libpng=1.6.30=1
- libxcb=1.12=1
- libxml2=2.9.4=0
- matplotlib=1.5.3=np111py27_1
- mkl=11.3.3=0
- numpy=1.11.2=py27_0
- openssl=1.0.2l=0
- pcre=8.39=1
- pip=9.0.1=py27_1
- pixman=0.34.0=0
- pycairo=1.10.0=py27_0
- pyparsing=2.2.0=py27_0
- pyqt=5.6.0=py27_2
- python=2.7.13=0
- python-dateutil=2.6.1=py27_0
- pytz=2017.2=py27_0
- qt=5.6.2=5
- readline=6.2=2
- scipy=0.17.1=np111py27_1
- setuptools=36.4.0=py27_1
- sip=4.18=py27_0
- six=1.10.0=py27_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- zlib=1.2.11=0
- pip:
  - pandas==0.19.1
  - shapely==1.5.17
  - xlrd==1.0.0
prefix: /home/lbechberger/miniconda/envs/ConceptualSpaces

